version: "1.0"

networks:
  app:
    driver: bridge

services:
  postgres:
    image: postgres:16.0
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app
  redis:
    container_name: redis-cache
    image: redis:8
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app

  spring-todo:
    build: .
    container_name: todo-application
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tododb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - app